<a href="https://colab.research.google.com/github/zadel28/nyu-python-public-policy/blob/master/HW3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [0]:
df = pd.read_csv('/content/drive/My Drive/Data for Python/cleaned_311_data_hw3.csv', header='infer')

In [4]:
df.head()

,Unnamed: 0,Unnamed: 0.1,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,bbl,borough,x_coordinate_(state_plane),y_coordinate_(state_plane),open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
0,238,238,39887282,08/01/2018 01:42:01 AM,08/14/2018 02:42:12 PM,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Park,10003.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEW YORK,NaN,NaN,Closed,08/15/2018 01:42:01 AM,The Department of Parks and Recreation has com...,08/14/2018 02:42:12 PM,0 Unspecified,NaN,Unspecified,NaN,NaN,PHONE,First Park,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,353,353,39889407,08/01/2018 03:20:07 AM,08/23/2018 11:15:00 AM,DPR,Department of Parks and Recreation,Maintenance or Facility,Garbage or Litter,Park,11434.0,NaN,NaN,NaN,NaN,BAISLEY BOULEVARD,MERRICK BOULEVARD,INTERSECTION,JAMAICA,NaN,NaN,Closed,08/04/2018 03:20:07 AM,The Service Request submitted did not have suf...,08/23/2018 11:15:00 AM,12 QUEENS,NaN,QUEENS,1048111.0,188479.0,PHONE,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.683778,-73.769744,"(40.68377771085733, -73.76974413109498)"
2,403,403,39893067,08/01/2018 04:19:15 AM,08/02/2018 08:19:55 AM,DPR,Department of Parks and Recreation,Maintenance or Facility,Hours of Operation,Park,11206.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BROOKLYN,NaN,NaN,Closed,08/04/2018 04:19:15 AM,The Department of Parks and Recreation has com...,08/02/2018 08:19:55 AM,01 BROOKLYN,NaN,BROOKLYN,NaN,NaN,MOBILE,Ten Eyck Plaza,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,655,655,39890578,08/01/2018 07:32:33 AM,08/16/2018 10:28:38 AM,DPR,Department of Parks and Recreation,Maintenance or Facility,Garbage or Litter,Park,11691.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAR ROCKAWAY,NaN,NaN,Closed,08/04/2018 07:32:33 AM,The Department of Parks and Recreation has com...,08/16/2018 10:28:38 AM,14 QUEENS,NaN,QUEENS,NaN,NaN,PHONE,Westbourne Playground,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,658,658,39896325,08/01/2018 07:33:12 AM,09/04/2018 05:38:02 PM,DPR,Department of Parks and Recreation,Maintenance or Facility,Garbage or Litter,Park,11355.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLUSHING,NaN,NaN,Closed,08/04/2018 07:33:12 AM,The condition was inspected and it was determi...,09/04/2018 05:38:02 PM,07 QUEENS,NaN,QUEENS,NaN,NaN,MOBILE,Maple Playground,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
set(df.descriptor)

{'Air Conditioning Problem',
 'American Flag',
 'Asbestos',
 'Bent/Loose',
 'Broken Fence',
 'Broken Glass',
 'Broken Lock',
 'Broken Water Fountain',
 'Broken Window',
 'Cave-in',
 'Coin or Card Did Not Register',
 'Concrete Barrier',
 'Crash Cushion Defect',
 'Credit Card Stuck in Meter',
 'Damaged Bench',
 'Damaged Leg or Pole Bent',
 'Damaged Other',
 'Damaged Telephone',
 'Damaged Toilet/Sink',
 'Damaged or Leaking Roof',
 'Damaged or Missing Ad Box',
 'Dead Animal',
 'Decorative Necklace Lighting',
 'Dirt, Debris, Litter Complaint',
 'Dirty/Graffiti',
 'Fallen Debris from Bridge',
 'Fence',
 'Flooded',
 'Garbage or Litter',
 'Graffiti',
 'Graffiti - Bridge',
 'Graffiti - Highway',
 'Graffiti or Vandalism',
 'Graffiti/Litter on Phone',
 'Grass/Weeds',
 'Guard Rail - Bridge',
 'Guard Rail - Highway',
 'Heating Problem',
 'High Grass',
 'Highway Fence',
 'Hours of Operation',
 'Lack of Supplies',
 'Leaky Roof',
 'Lighting',
 'Litter',
 'Loose Plate',
 'Lost Coin',
 'Missing/Stump',
 'New Automatic Public Toilet Request',
 'No Dial Tone',
 'No Receipt',
 'Other School Condition',
 'Out of Order',
 'Painted Line/Marking',
 'Parking Card Stuck in Meter',
 'Phone Blocking Sidewalk',
 'Plumbing Problem',
 'Poison Ivy',
 'Police Report Not Requested',
 'Police Report Requested',
 'Pothole',
 'Pothole - Highway',
 'Relocation of Parking Meter',
 'Rodent Sighting',
 'Rodents/Mice',
 'Rough Pavement',
 'Sign Blocked by Tree',
 'Sign Missing or Defective',
 'Snow Removal Requested',
 'Snow on Overpass',
 'Snow or Ice',
 'Snow/Ice',
 'Structure - Indoors',
 'Structure - Outdoors',
 'Timer Defect - Fast/Fail',
 'Unclean Condition',
 'Unsafe Worksite',
 'Unsecured Facility'}

In [0]:
# Convert descriptor to lowercase
df.descriptor.str.lower()
df.descriptor = df.descriptor.str.lower()

In [0]:
# Convert complaint type to lowercase
df.complaint_type.str.lower()
df.complaint_type = df.complaint_type.str.lower()

In [8]:
set(df.descriptor)

{'air conditioning problem',
 'american flag',
 'asbestos',
 'bent/loose',
 'broken fence',
 'broken glass',
 'broken lock',
 'broken water fountain',
 'broken window',
 'cave-in',
 'coin or card did not register',
 'concrete barrier',
 'crash cushion defect',
 'credit card stuck in meter',
 'damaged bench',
 'damaged leg or pole bent',
 'damaged or leaking roof',
 'damaged or missing ad box',
 'damaged other',
 'damaged telephone',
 'damaged toilet/sink',
 'dead animal',
 'decorative necklace lighting',
 'dirt, debris, litter complaint',
 'dirty/graffiti',
 'fallen debris from bridge',
 'fence',
 'flooded',
 'garbage or litter',
 'graffiti',
 'graffiti - bridge',
 'graffiti - highway',
 'graffiti or vandalism',
 'graffiti/litter on phone',
 'grass/weeds',
 'guard rail - bridge',
 'guard rail - highway',
 'heating problem',
 'high grass',
 'highway fence',
 'hours of operation',
 'lack of supplies',
 'leaky roof',
 'lighting',
 'litter',
 'loose plate',
 'lost coin',
 'missing/stump',
 'new automatic public toilet request',
 'no dial tone',
 'no receipt',
 'other school condition',
 'out of order',
 'painted line/marking',
 'parking card stuck in meter',
 'phone blocking sidewalk',
 'plumbing problem',
 'poison ivy',
 'police report not requested',
 'police report requested',
 'pothole',
 'pothole - highway',
 'relocation of parking meter',
 'rodent sighting',
 'rodents/mice',
 'rough pavement',
 'sign blocked by tree',
 'sign missing or defective',
 'snow on overpass',
 'snow or ice',
 'snow removal requested',
 'snow/ice',
 'structure - indoors',
 'structure - outdoors',
 'timer defect - fast/fail',
 'unclean condition',
 'unsafe worksite',
 'unsecured facility'}

Create a function that checks each row in the 311 dataframe to see if the word "graffiti" is present in either the complaint_type value or descriptor value. Both columns may contain the word, so you should check both. If the word "graffiti" is found, the function should return the boolean value True. If "graffiti" is not found, the function should return the boolean value False.

In [9]:
# Create a function graffiti that flags if complaint type or descriptor contains graffiti
def graffiti(row):
  if pd.notnull(row.descriptor):
    if 'graffiti' in row.descriptor:
      return 'True'
    elif 'graffiti' in row.complaint_type:
      return 'True'
    else:
      return 'False'

type(graffiti)

function

In [10]:
# Apply function that creates new column true/false for whether complaint or descriptor contains graffiti
df['graffiti_flag'] = df.apply(graffiti, axis=1)
df.head()

,Unnamed: 0,Unnamed: 0.1,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,bbl,borough,x_coordinate_(state_plane),y_coordinate_(state_plane),open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location,graffiti_flag
0,238,238,39887282,08/01/2018 01:42:01 AM,08/14/2018 02:42:12 PM,DPR,Department of Parks and Recreation,maintenance or facility,structure - outdoors,Park,10003.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEW YORK,NaN,NaN,Closed,08/15/2018 01:42:01 AM,The Department of Parks and Recreation has com...,08/14/2018 02:42:12 PM,0 Unspecified,NaN,Unspecified,NaN,NaN,PHONE,First Park,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,353,353,39889407,08/01/2018 03:20:07 AM,08/23/2018 11:15:00 AM,DPR,Department of Parks and Recreation,maintenance or facility,garbage or litter,Park,11434.0,NaN,NaN,NaN,NaN,BAISLEY BOULEVARD,MERRICK BOULEVARD,INTERSECTION,JAMAICA,NaN,NaN,Closed,08/04/2018 03:20:07 AM,The Service Request submitted did not have suf...,08/23/2018 11:15:00 AM,12 QUEENS,NaN,QUEENS,1048111.0,188479.0,PHONE,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.683778,-73.769744,"(40.68377771085733, -73.76974413109498)",False
2,403,403,39893067,08/01/2018 04:19:15 AM,08/02/2018 08:19:55 AM,DPR,Department of Parks and Recreation,maintenance or facility,hours of operation,Park,11206.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BROOKLYN,NaN,NaN,Closed,08/04/2018 04:19:15 AM,The Department of Parks and Recreation has com...,08/02/2018 08:19:55 AM,01 BROOKLYN,NaN,BROOKLYN,NaN,NaN,MOBILE,Ten Eyck Plaza,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
3,655,655,39890578,08/01/2018 07:32:33 AM,08/16/2018 10:28:38 AM,DPR,Department of Parks and Recreation,maintenance or facility,garbage or litter,Park,11691.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAR ROCKAWAY,NaN,NaN,Closed,08/04/2018 07:32:33 AM,The Department of Parks and Recreation has com...,08/16/2018 10:28:38 AM,14 QUEENS,NaN,QUEENS,NaN,NaN,PHONE,Westbourne Playground,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4,658,658,39896325,08/01/2018 07:33:12 AM,09/04/2018 05:38:02 PM,DPR,Department of Parks and Recreation,maintenance or facility,garbage or litter,Park,11355.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLUSHING,NaN,NaN,Closed,08/04/2018 07:33:12 AM,The condition was inspected and it was determi...,09/04/2018 05:38:02 PM,07 QUEENS,NaN,QUEENS,NaN,NaN,MOBILE,Maple Playground,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [11]:
# Create a dataframe that groups by graffiti flag
df_2 = df.groupby('graffiti_flag').size().reset_index(name='count')

# Check to confirm that the function worked
df_2

  graffiti_flag  count
0         False  38206
1          True  26371

In [12]:
# Check to make sure that more than one complaint_type is included
df_3 = df[df.graffiti_flag == 'True'].groupby('complaint_type').size().reset_index(name='count')

df_3

               complaint_type  count
0            bridge condition     60
1        broken parking meter     83
2  bus stop shelter complaint    187
3                    graffiti  24986
4           highway condition    310
5     maintenance or facility    577
6   public payphone complaint    112
7               public toilet     10
8          school maintenance     46

In [0]:
# Create another dataframe df_graffiti that only contains records where graffiti_flag is True 
df_graffiti = df[df.graffiti_flag == 'True']

In [16]:
df_graffiti.head(20)

,Unnamed: 0,Unnamed: 0.1,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,bbl,borough,x_coordinate_(state_plane),y_coordinate_(state_plane),open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location,graffiti_flag
8,860,860,39897352,08/01/2018 08:21:08 AM,NaN,DSNY,Department of Sanitation,graffiti,graffiti,NaN,NaN,141 141 ST,141 ST,NaN,NaN,NaN,NaN,ADDRESS,NaN,NaN,NaN,Open,NaN,NaN,08/01/2018 08:21:08 AM,Unspecified QUEENS,NaN,QUEENS,NaN,NaN,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
9,876,876,39891938,08/01/2018 08:24:41 AM,08/30/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11237.0,237 IRVING AVENUE,IRVING AVENUE,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/20/2018 03:18:01 PM,04 BROOKLYN,3.032900e+09,BROOKLYN,1007216.0,194542.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.700620,-73.917173,"(40.70061981717157, -73.91717344071574)",True
10,964,964,39897349,08/01/2018 08:40:34 AM,08/23/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Residential,10467.0,345 EAST 205 STREET,EAST 205 STREET,NaN,NaN,NaN,NaN,ADDRESS,BRONX,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,07 BRONX,2.033500e+09,BRONX,1018509.0,257554.0,UNKNOWN,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.873534,-73.876124,"(40.87353414980636, -73.87612406980227)",True
12,1007,1007,39893314,08/01/2018 08:47:45 AM,08/20/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11220.0,5506 5 AVENUE,5 AVENUE,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,07 BROOKLYN,3.008310e+09,BROOKLYN,980544.0,173249.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.642204,-74.013354,"(40.64220432954161, -74.01335393443593)",True
13,1013,1013,39897422,08/01/2018 08:49:15 AM,08/28/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11237.0,884 HART STREET,HART STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,04 BROOKLYN,3.032360e+09,BROOKLYN,1005915.0,195340.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.702813,-73.921863,"(40.70281342017164, -73.92186290937498)",True
15,1113,1113,39890371,08/01/2018 09:05:14 AM,08/20/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Residential,11222.0,39 NORTH HENRY STREET,NORTH HENRY STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,01 BROOKLYN,3.028270e+09,BROOKLYN,1000125.0,201791.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.720532,-73.942730,"(40.720532158642264, -73.94272993232262)",True
16,1125,1125,39890363,08/01/2018 09:06:03 AM,10/03/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Residential,11222.0,37 NORTH HENRY STREET,NORTH HENRY STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,10/10/2018 09:00:21 AM,The City has removed the graffiti from this pr...,10/23/2018 02:36:05 PM,01 BROOKLYN,3.028278e+09,BROOKLYN,1000129.0,201759.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.720444,-73.942716,"(40.72044431919613, -73.94271557756703)",True
21,1361,1361,39897421,08/01/2018 09:34:51 AM,08/27/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11207.0,830 KNICKERBOCKER AVENUE,KNICKERBOCKER AVENUE,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,04 BROOKLYN,3.034240e+09,BROOKLYN,1010201.0,191407.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.692007,-73.906420,"(40.692006725226506, -73.90642016600616)",True
22,1379,1379,39894550,08/01/2018 09:37:09 AM,09/24/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Residential,11233.0,663 MACDONOUGH STREET,MACDONOUGH STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,10/10/2018 09:00:21 AM,"The cleaning crew was dispatched, but the owne...",10/03/2018 01:02:01 PM,03 BROOKLYN,3.014970e+09,BROOKLYN,1006583.0,188415.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.683804,-73.919477,"(40.68380424457166, -73.91947665760173)",True
23,1383,1383,39898718,08/01/2018 09:37:50 AM,09/24/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Residential,11233.0,661 MACDONOUGH STREET,MACDONOUGH STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,10/10/2018 09:00:21 AM,The City has removed the graffiti from this pr...,10/03/2018 01:02:01 PM,03 BROOKLYN,3.014970e+09,BROOKLYN,1006568.0,188413.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.683799,-73.919531,"(40.6837987928642, -73.9195307478448)",True
25,1507,1507,39896760,08/01/2018 09:47:21 AM,NaN,DSNY,Department of Sanitation,graffiti,graffiti,Comercial,11222.0,239 INDIA STREET,INDIA STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Open,09/06/2018 10:04:56 AM,The graffiti on this property has been schedul...,08/07/2018 10:04:56 AM,01 BROOKLYN,3.025340e+09,BROOKLYN,998030.0,206239.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.732744,-73.950279,"(40.73274434563595, -73.95027866755898)",True
26,1521,1521,39895320,08/01/2018 09:49:12 AM,09/24/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Comercial,11435.0,137-77 QUEENS BOULEVARD,QUEENS BOULEVARD,NaN,NaN,NaN,NaN,ADDRESS,Jamaica,NaN,NaN,Closed,10/10/2018 09:00:21 AM,The City has removed the graffiti from this pr...,10/03/2018 01:02:01 PM,08 QUEENS,4.096510e+09,QUEENS,1034498.0,197615.0,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.708942,-73.818759,"(40.708941601133574, -73.81875856157347)",True
27,1545,1545,39893313,08/01/2018 09:51:45 AM,11/05/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11435.0,138-76 QUEENS BOULEVARD,QUEENS BOULEVARD,NaN,NaN,NaN,NaN,ADDRESS,Jamaica,NaN,NaN,Closed,10/10/2018 09:00:21 AM,The cleaning crew could not locate the propert...,12/27/2018 03:04:35 PM,08 QUEENS,4.096440e+09,QUEENS,1034971.0,196856.0,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.706856,-73.817058,"(40.706855631355445, -73.81705820212048)",True
30,1718,1718,39896802,08/01/2018 10:11:55 AM,08/17/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Comercial,11210.0,848 EAST 43 STREET,EAST 43 STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,17 BROOKLYN,3.077260e+09,BROOKLYN,1002199.0,170405.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.634381,-73.935331,"(40.634380746832456, -73.93533143824904)",True
37,2006,2006,39899215,08/01/2018 10:42:16 AM,08/01/2018 11:16:34 AM,NYPD,New York City Police Department,graffiti,police report not requested,Street/Sidewalk,11417.0,138-30 LAFAYETTE STREET,LAFAYETTE STREET,ALBERT ROAD,149 AVENUE,NaN,NaN,ADDRESS,OZONE PARK,NaN,Precinct,Closed,08/01/2018 06:42:16 PM,The Police Department responded to the complai...,08/01/2018 11:16:34 AM,10 QUEENS,4.114030e+09,QUEENS,1027208.0,183865.0,PHONE,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.671239,-73.845141,"(40.67123947322719, -73.84514076011867)",True
41,2139,2139,39896075,08/01/2018 10:58:27 AM,08/28/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,10027.0,2031 ACP BOULEVARD,ACP BOULEVARD,NaN,NaN,NaN,NaN,ADDRESS,NEW YORK,NaN,NaN,Closed,09/06/2018 10:04:56 AM,"The cleaning crew was dispatched, but the owne...",09/13/2018 04:19:12 PM,10 MANHATTAN,1.019060e+09,MANHATTAN,998109.0,233201.0,UNKNOWN,Unspecified,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.806748,-73.949938,"(40.806747877888995, -73.94993801936936)",True
43,2178,2178,39897385,08/01/2018 11:02:40 AM,08/23/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Residential,10452.0,80 WEST 167 STREET,WEST 167 STREET,NaN,NaN,NaN,NaN,ADDRESS,BRONX,NaN,NaN,Closed,09/06/2018 10:04:56 AM,"The City inspected the property for cleaning, ...",09/20/2018 03:18:01 PM,04 BRONX,2.025130e+09,BRONX,1004882.0,244005.0,UNKNOWN,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.836389,-73.925439,"(40.83638857288985, -73.92543913529472)",True
46,2199,2199,39895981,08/01/2018 11:05:57 AM,08/22/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,NaN,10469.0,1458 GUN HILL ROAD,GUN HILL ROAD,NaN,NaN,NaN,NaN,ADDRESS,BRONX,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/20/2018 03:18:01 PM,11 BRONX,2.045670e+09,BRONX,1027457.0,255981.0,UNKNOWN,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.869177,-73.843780,"(40.86917748688064, -73.84377951187668)",True
47,2212,2212,39894740,08/01/2018 11:07:51 AM,08/21/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11435.0,113-12 SUTPHIN BOULEVARD,SUTPHIN BOULEVARD,NaN,NaN,NaN,NaN,ADDRESS,Jamaica,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/20/2018 03:18:01 PM,12 QUEENS,4.119660e+09,QUEENS,1041306.0,189550.0,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.686764,-73.794271,"(40.686763833998235, -73.79427093015273)",True
48,2241,2241,39888488,08/01/2018 11:10:24 AM,08/20/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Comercial,11433.0,106-24 157 STREET,157 STREET,NaN,NaN,NaN,NaN,ADDRESS,Jamaica,NaN,NaN,Closed,09/06/2018 10:04:56 AM,"The cleaning crew was dispatched, but the owne...",09/13/2018 04:19:12 PM,12 QUEENS,4.101240e+09,QUEENS,1040406.0,193445.0,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.697460,-73.797484,"(40.69746043689861, -73.79748361485751)",True

In [15]:
# Identify which Community District has the highest count

df_graffiti.groupby('community_board').size().nlargest().reset_index(name='count')

  community_board  count
0     01 BROOKLYN   1797
1    03 MANHATTAN   1593
2     04 BROOKLYN   1429
3     03 BROOKLYN   1252
4     05 BROOKLYN    962